logFilters:
  - code: YN0076
    level: discard

nodeLinker: node-modules

packageExtensions:
  '@remix-run/express@*': &react
    peerDependencies:
      react: '>=17'
      react-dom: '>=17'
  '@remix-run/node@*': *react
  '@remix-run/serve@*': *react
  '@remix-run/vercel@*': *react

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v2"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
