nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://github.com/mskelton/yarn-plugin-outdated/raw/v2/bundles/@yarnpkg/plugin-outdated.js"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
