app = "mskelton-dev"
primary_region = "ord"
swap_size_mb = 512
[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[mounts]]
source = "libsql_data"
destination = "/app/data"
