export const roles = [
  {
    company: "Federato",
    date: "March 2023 - Present",
    href: "https://federato.ai",
    responsibilities: [
      "Developed an admin portal which significantly improved time to delivery of customization and features",
      "Built and maintained a design system using React, Tailwind, and Storybook",
      "Constructed a GraphQL federated gateway using Apollo with custom plugins developed in Rust decreasing average latency by 7x and maximum latency from ~10s to ~40ms",
      "Architected a database introspection and query tool with capabilities to support custom data schemas for customers with tight integration into frontend components",
      "Maintained an extremely feature rich and highly configurable data table used in roughly 70% of the application for customers to manage their data",
      "Implemented significant improvements to build process to improve developer efficiency",
      "Mentoring developers, knowledge sharing, and teaching techniques for improving engineering skills",
    ],
    title: "Staff Software Enginer",
  },
  {
    company: "Widen, an Acquia Company",
    date: "January 2019 - February 2023",
    href: "https://www.acquia.com/products/acquia-dam",
    responsibilities: [
      "Refactored large portions of a legacy monolith into microservices",
      "Developed frontend React applications in collaboration with designers",
      "Lead developer of React component and utility libraries used throughout the company",
      "Created a distributed architecture using module federation",
      "Drove the company-wide frontend architecture planning",
      "Developing a internal browser extension to simplify common development tasks",
      "Architected and developed a bulk data import tool capable of processing a quarter million records",
    ],
    title: "Staff Software Engineer",
  },
  {
    company: "Computer Know How",
    date: "August 2016 - January 2019",
    href: "https://ckhconsulting.com",
    responsibilities: [
      "Consulting with customers to define their technical needs, then designing and executing a solution to meet them",
      "Leading development for an enterprise level Single Sign-On application including reporting and analytics functionality, using Node.js and Vue.js",
      "Architecting a time tracking application that integrates seamlessly with QuickBooks using Node.js on the back-end, Angular/Ionic on the front-end, deployed with Docker",
      "Creating a payment processing API with bi-directional support for multiple payment gateways, transforming data from disparate sources into a unified format",
      "Traveling onsite to customers for at-the-elbow troubleshooting for development issues",
      "Communicating effectively with customers and cross-role internal stakeholders",
      "Participating and/or leading the entire development life cycle from requirement elicitation sessions to design, development, testing, and support",
    ],
    title: "Web Developer",
  },
]
