name: Build
on: [push]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v1
      - run: yarn lint
      - run: yarn prettier --check .
  ts:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v1
      - run: yarn ts
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.1
        with:
          args: deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  e2e:
    name: End-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v1
      - run: yarn playwright install chromium --with-deps
      - run: yarn test
        # env:
        #   PLAYWRIGHT_TEST_BASE_URL:
        #     ${{ github.event.deployment_status.target_url }}
      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: test-results
          path: test-results
