name: Playwright Tests
on: [deployment_status]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - uses: mskelton/setup-pnpm@v2
      - run: pnpm playwright install chromium --with-deps
      - run: pnpm test
        env:
          BASE_URL: ${{ github.event.deployment_status.target_url }}
      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: test-results
          path: test-results
