name: Tickle DB
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  tickle:
    name: Tickle DB
    runs-on: ubuntu-latest
    steps:
      - name: Tickle DB
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.TURSO_AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"statements": ["SELECT count(id) FROM bytes"]}' \
            ${{ secrets.TURSO_DATABASE_URL }}
